//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BangLuong
    {
        [DisplayName(" Mã Nhân Viên")]
        public string MaNV { get; set; }
        [DisplayName(" Số Ngày Công ")]
        public Nullable<int> SoNgayCong { get; set; }
        [DisplayName(" Lương")]
        public Nullable<double> Luong { get; set; }
        [DisplayName(" Thực Lĩnh")]
        public Nullable<double> ThucLinh { get; set; }
        [DisplayName(" Mã Nhân Viên")]
        public virtual NhanVien NhanVien { get; set; }
    }
}
