//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
        [DisplayName("Mã Hợp Đồng")]
        public string MaHD { get; set; }
        [DisplayName("Tên Hợp Đồng")]
        public string TenHD { get; set; }
        [DisplayName("Tên Nhân Viên")]
        public string TenNV { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string SDT { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Địa Chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Giới Tính")]
        public string GioiTinh { get; set; }
        [DisplayName("Ngày Sinh")]
        public string NgaySinh { get; set; }
        [DisplayName("Ngày Kí Hợp Đồng")]
        public string NgayKiHopDong { get; set; }
        [DisplayName("Thời Hạn")]
        public string ThoiHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
